USE Final_EX;

-- STRIGGER AUTO COUNT MEMBER


    -- DROP TRIGGER IF EXISTS INS_SUM;

-- DELIMITER $$
-- CREATE TRIGGER INS_SUM AFTER UPDATE ON `USER`
-- FOR EACH ROW
-- BEGIN
-- 	WITH B1 AS(
-- SELECT COUNT(USER_NAME)FROM USER JOIN GROUP_M ON GROUP_M.ID = USER.GROUP_ID GROUP BY GROUP_ID

--     UPDATE GROUP_M 
--     SET `MEMBER` = B1.COUNT_GR
--     WHERE GROUP_M.ID = B1.GROUP_ID;

-- END$$
-- DELIMITER ;



    
    